AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
  UseExternalELBCertificateCondition: !Equals [!Ref UseExternalELBCertificate, 'true']
  UseInternalDefaultELBCertificateCondition: !Equals [!Ref UseInternalDefaultELBCertificate, 'true']
Description: Overarching CF Template to Create AEM Full-Set Main Resources Stacks (qs-1r4pm2nq7)
Parameters:
  AuthorDispatcherInstanceTypeParameter:
    Description: The Author Dispatcher Instance Type
    Type: String
  AuthorInstanceTypeParameter:
    Description: The Author Instance Type
    Type: String
  DataBucketNameParameter:
    Description: Bucket name that stores Stack data files
    Type: String
  AOCStackPrefix:
    Description: The AEM Stack Compute Resources Stack Prefix
    Type: String
  ExternalCertificateARN:
    Default: ''
    Description: (Optional) The ARN of the external Certificate stored in AWS Certificate Manager(ACM).
      If not provided, but External FQDN & External Route53 Zone ID were provided, an external wildcard certificate will be created for you.
    Type: String
  OrchestratorInstanceTypeParameter:
    Description: The Orchestrator Instance Type
    Type: String
  PublishDispatcherInstanceTypeParameter:
    Description: The Publish Dispatcher Instance Type
    Type: String
  PublishDispatcherLoadBalancerSchemeParameter:
    Description: AEM Publish Dispatcher ELB Scheme
    Type: String
  PublishInstanceTypeParameter:
    Description: The Publish Instance Type
    Type: String
  UseExternalELBCertificate:
    Description: Set to true to use external Certifiacte for Publish-Dispatcher ELB
    Default: 'false'
    Type: String
  UseInternalDefaultELBCertificate:
    Description: Set to true to use internal Certifiacte for ELB
    Default: 'true'
    Type: String
  Route53InternalHostedZoneID:
    Description: Internal Route53 Hosted Zone ID
    Type: String
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
    Default: ap-southeast-2
    Description: The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: >-
      AWS Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/). It cannot start or end with forward
      slash (/) because they are automatically appended.
    Default: quickstart-aem-opencloud/
    Description: >-
      S3 key prefix for the AWS Quick Start assets.AWS Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and forward
      slash (/). It cannot start or end with forward slash (/) because they are automatically
      appended.
    Type: String
Resources:
  AuthorDispatcherStack:
    Properties:
      Parameters:
        AemAwsStackProvisionerVersionParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/version/aemawsstackprovisioner:1}}"
        AuthorDispatcherASGAvailabilityZoneListParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/network/availabilityzones:1}}"
        AuthorDispatcherImageParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/ec2/images/dispatcher:1}}"
        AuthorDispatcherImageRootDevice: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/rootdevice:1}}"
        AuthorDispatcherImageDataDevice: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/datadevice:1}}"
        AuthorDispatcherInstanceTypeParameter:
          Ref: AuthorDispatcherInstanceTypeParameter
        AuthorDispatcherRootVolSizeParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/authordispatcher/rootvolume/size:1}}"
        AuthorDispatcherDataVolSizeParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/authordispatcher/datavolume/size:1}}"
        AuthorDispatcherDataVolSnapshotParameter: ''
        UseAuthorDispatcherDataVolSnapshotParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/authordispatcher/datavolume/backupenabled:1}}"
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        AOCStackPrefix:
          Ref: AOCStackPrefix
        SSLCertificateARNParameter: !If
          - UseInternalDefaultELBCertificateCondition
          - !Sub "{{resolve:ssm:/${AOCStackPrefix}/cert/defaultinternal:1}}"
          - !Sub "{{resolve:ssm:/${AOCStackPrefix}/cert/internal:1}}"
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/full-set/author-dispatcher.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
    Type: AWS::CloudFormation::Stack
  AuthorStack:
    Properties:
      Parameters:
        AemAwsStackProvisionerVersionParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/version/aemawsstackprovisioner:1}}"
        AuthorImageParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/ec2/images/author:1}}"
        AuthorImageRootDevice: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/rootdevice:1}}"
        AuthorImageDataDevice: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/datadevice:1}}"
        AuthorInstanceTypeParameter:
          Ref: AuthorInstanceTypeParameter
        AuthorRootVolSizeParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/author/rootvolume/size:1}}"
        AuthorDataVolSizeParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/author/datavolume/size:1}}"
        AuthorDataVolSnapshotParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/author/datavolume/backupid:1}}"
        UseAuthorDataVolSnapshotParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/author/datavolume/usebackup:1}}"
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        AOCStackPrefix:
          Ref: AOCStackPrefix
        SSLCertificateARNParameter: !If
          - UseInternalDefaultELBCertificateCondition
          - !Sub "{{resolve:ssm:/${AOCStackPrefix}/cert/defaultinternal:1}}"
          - !Sub "{{resolve:ssm:/${AOCStackPrefix}/cert/internal:1}}"
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/full-set/author.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
    Type: AWS::CloudFormation::Stack
  DNSRecordStack:
    DependsOn:
    - AuthorDispatcherStack
    - AuthorStack
    - PublishDispatcherStack
    Properties:
      Parameters:
        AOCStackPrefix:
          Ref: AOCStackPrefix
        Route53InternalHostedZoneID: !Ref Route53InternalHostedZoneID
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/full-set/dns-records.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
    Type: AWS::CloudFormation::Stack
  OrchestratorStack:
    Properties:
      Parameters:
        AEMASGEventQueueName: !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/aemasgeventqueuename:1}}"
        AemAwsStackProvisionerVersionParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/version/aemawsstackprovisioner:1}}"
        AuthorDispatcherStackArn:
          Ref: AuthorDispatcherStack
        AuthorStackArn:
          Ref: AuthorStack
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        AOCStackPrefix:
          Ref: AOCStackPrefix
        MessagingStackArn: !Sub "{{resolve:ssm:/${AOCStackPrefix}/messaging/stackname:1}}"
        OrchestratorASGAvailabilityZoneListParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/network/availabilityzones:1}}"
        OrchestratorImageParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/ec2/images/java:1}}"
        OrchestratorImageRootDevice: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/rootdevice:1}}"
        OrchestratorImageDataDevice: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/datadevice:1}}"
        OrchestratorInstanceTypeParameter:
          Ref: OrchestratorInstanceTypeParameter
        OrchestratorRootVolSizeParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/orchestrator/rootvolume/size:1}}"
        OrchestratorDataVolSizeParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/orchestrator/datavolume/size:1}}"
        PublishDispatcherStackName:
          # As of May '18, CloudFormation doesn't provide a way to retrieve the Stack Name with Fn::GetAtt or Ref functions
          # Resorting to parsing the ARN to obtain it
          # See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html
          #      https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html
          Fn::Select:
            - 1
            - Fn::Split:
              - /
              - Ref: PublishDispatcherStack
        PublishStackArn:
          Ref: PublishStack
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/full-set/orchestrator.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
    Type: AWS::CloudFormation::Stack
  PublishDispatcherStack:
    Properties:
      Parameters:
        AemAwsStackProvisionerVersionParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/version/aemawsstackprovisioner:1}}"
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        AOCStackPrefix:
          Ref: AOCStackPrefix
        PublishDispatcherASGAvailabilityZoneListParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/network/availabilityzones:1}}"
        PublishDispatcherRootVolSizeParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/publishdispatcher/rootvolume/size:1}}"
        PublishDispatcherDataVolSizeParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/publishdispatcher/datavolume/size:1}}"
        PublishDispatcherDataVolSnapshotParameter: ''
        UsePublishDispatcherDataVolSnapshotParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/publishdispatcher/datavolume/backupenabled:1}}"
        PublishDispatcherImageParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/ec2/images/dispatcher:1}}"
        PublishDispatcherImageRootDevice: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/rootdevice:1}}"
        PublishDispatcherImageDataDevice: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/datadevice:1}}"
        PublishDispatcherInstanceTypeParameter:
          Ref: PublishDispatcherInstanceTypeParameter
        PublishDispatcherLoadBalancerSchemeParameter:
          Ref: PublishDispatcherLoadBalancerSchemeParameter
        SSLCertificateARNParameter: !If
          - UseExternalELBCertificateCondition
          - !Ref ExternalCertificateARN
          - !If
            - UseInternalDefaultELBCertificateCondition
            - !Sub "{{resolve:ssm:/${AOCStackPrefix}/cert/defaultinternal:1}}"
            - !Sub "{{resolve:ssm:/${AOCStackPrefix}/cert/internal:1}}"
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/full-set/publish-dispatcher.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
    Type: AWS::CloudFormation::Stack
  PublishStack:
    Properties:
      Parameters:
        AemAwsStackProvisionerVersionParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/version/aemawsstackprovisioner:1}}"
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        AOCStackPrefix:
          Ref: AOCStackPrefix
        PublishASGAvailabilityZoneListParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/network/availabilityzones:1}}"
        PublishRootVolSizeParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/publish/rootvolume/size:1}}"
        PublishDataVolSizeParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/publish/datavolume/size:1}}"
        PublishDataVolSnapshotParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/publish/datavolume/backupid:1}}"
        UsePublishDataVolSnapshotParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/publish/datavolume/usebackup:1}}"
        PublishImageParameter: !Sub "{{resolve:ssm:/${AOCStackPrefix}/ec2/images/publish:1}}"
        PublishImageRootDevice: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/rootdevice:1}}"
        PublishImageDataDevice: !Sub "{{resolve:ssm:/${AOCStackPrefix}/config/datadevice:1}}"
        PublishInstanceTypeParameter:
          Ref: PublishInstanceTypeParameter
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/full-set/publish.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
    Type: AWS::CloudFormation::Stack
Outputs:
  AuthorDNSRecord:
    Description: The Route53 record of the Author ELB
    Value: !GetAtt 'DNSRecordStack.Outputs.AuthorDNSRecord'
  AuthorDispatcherDNSRecord:
    Description: The Route53 record of the Author-Dispatcher ELB
    Value: !GetAtt 'DNSRecordStack.Outputs.AuthorDispatcherDNSRecord'
  PublishDispatcherDNSRecord:
    Description: The Route53 record of the Publish-Dispatcher ELB
    Value: !GetAtt 'DNSRecordStack.Outputs.PublishDispatcherDNSRecord'
  AuthorDispatcherLoadBalancerDNSName:
    Description: The Route53 record of the Author-Dispatcher ELB
    Value: !GetAtt 'AuthorDispatcherStack.Outputs.AuthorDispatcherLoadBalancerDNSName'
  PublishDispatcherLoadBalancerDNSName:
    Description: The Route53 record of the Publish-Dispatcher ELB
    Value: !GetAtt 'PublishDispatcherStack.Outputs.PublishDispatcherLoadBalancerDNSName'
